version: '3.8'

services:
  app:
    image: ghcr.io/magicsales2/beauty-spin:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty_spin_app
    restart: always
    ports:
      # Puerto libre fallback para que pruebes tu aplicación directamente por IP (http://TU_IP_VPS:3080)
      - "3080:8080"
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      # Dominio o subdominio asignado a tu aplicación
      - "traefik.http.routers.beauty_spin1.rule=Host(`beauty_spin1.srv1758628.hstgr.cloud`)"
      - "traefik.http.routers.beauty_spin1.entrypoints=websecure"
      - "traefik.http.routers.beauty_spin1.tls=true"
      - "traefik.http.routers.beauty_spin1.tls.certresolver=letsencrypt"
      
      # Indica a Traefik que el puerto interno del contenedor es el 8080 (donde escucha Nginx)
      - "traefik.http.services.beauty_spin1.loadbalancer.server.port=8080"

networks:
  proxy_network:
    external: true

